command:
  - gunicorn
  - app:server
  - --bind
  - "0.0.0.0:8000"
  - --workers
  - "2"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: "sql-warehouse"
  - name: NEMWEB_CATALOG
    value: "daveok"
  - name: NEMWEB_SCHEMA
    value: "ml_workshops"

resources:
  - name: "sql-warehouse"
    sql_warehouse:
      id: "e4082fdb7ea19a15"
      permission: CAN_USE
