command:
  - gunicorn
  - app:server
  - --bind
  - 0.0.0.0:8000
  - --workers
  - "2"

env:
  - name: NEMWEB_DATA_SOURCE
    value: delta
  - name: NEMWEB_DELTA_TABLE
    value: agl.nemweb.dispatch_region
  - name: NEMWEB_LIVE_INTERVALS
    value: "12"
